# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-09 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_auto_20170409_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='age',
        ),
        migrations.RemoveField(
            model_name='people',
            name='job',
        ),
        migrations.AddField(
            model_name='people',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
