# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20170410_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='password',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
