# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_auto_20170424_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
