# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_auto_20170424_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
